- name: Check for security updates across all systems
  hosts: all
  gather_facts: true
  become: true

  vars:
    security_updates: []

  tasks:
    - name: Ensure unattended-upgrades is installed (Debian/Ubuntu only)
      apt:
        name: unattended-upgrades
        state: present
        update_cache: true
      when: ansible_facts['os_family'] == 'Debian'

    - name: Check for security updates (Debian/Ubuntu)
      shell: unattended-upgrade --dry-run -d | grep -i security || true
      register: sec_updates
      changed_when: false
      when: ansible_facts['os_family'] == 'Debian'

    - name: Set fact for cleaned update list
      set_fact:
        security_updates: "{{ sec_updates.stdout_lines | default([]) }}"
      when: ansible_facts['os_family'] == 'Debian'

    - name: Show security update summary
      debug:
        msg: |
          Host: {{ inventory_hostname }}
          {% if security_updates | length > 0 %}
          Security Updates:
          {{ security_updates | join('\n') }}
          {% else %}
          No security updates found or system not applicable.
          {% endif %}
