---
- name: Install Zabbix agent on all hosts
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Install dependencies (Debian-based)
      apt:
        name: wget
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Zabbix repo (Debian-based)
      apt:
        deb: "https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-4+debian{{ ansible_distribution_major_version }}_all.deb"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install dependencies (RedHat-based)
      yum:
        name: wget
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Zabbix repo (RedHat-based)
      yum:
        name: "https://repo.zabbix.com/zabbix/6.0/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-6.0-4.el{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Zabbix agent
      package:
        name: zabbix-agent
        state: present

    - name: Enable and start zabbix-agent
      service:
        name: zabbix-agent
        enabled: true
        state: started
